### ISSUE TITLE
Reindexing ideal variables

### ISSUE THREAD

**Issue by PennyWieser** [gleesonm1/pyMELTScalc#2]
To convert to dictionary for any user input
Matt needs to change Fe3Fet_Liq
`df_ideal_MELTS = pd.DataFrame(columns=['SiO2_Liq', 'TiO2_Liq', 'Al2O3_Liq',
'FeOt_Liq',  'MgO_Liq', 'CaO_Liq', 'Na2O_Liq', 'K2O_Liq',
'P2O5_Liq',  'MnO_Liq', 'CO2_Liq', 'H2O_Liq', 'Fe3Fet_Liq'])

df_ideal_MELTS2=df_ideal_MELTS.rename(columns={'Fe3Fet_Liq': 'Fe3Fet'}).to_dict()

test4=test3.reindex(df_ideal_MELTS2, axis=1).fillna(0)
test5=test4.to_dict()`

**Comment by PennyWieser** [comment]
Add Fe3Fet_Liq into the functions itself as an override

**Comment by gleesonm1** [comment]
In v0.0.7 Fe3Fet_Liq and H2O_Liq can be included as separate input parameters in most functions. Doing so will overwrite the Fe3Fet_Liq and H2O_Liq values in the comp file. The input dictionary/dataframe will also now be converted to contain the correct keys (e.g., SiO2 will become SiO2_Liq).
